server:
  port: 8662

spring:
  application:
    name: security-gateway-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtappdb?serverTimezone=UTC
    username: root
    password: admin
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:mysql://localhost:3306/jwtappdb?serverTimezone=UTC
    user: root
    password: admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
ribbon:
  ReadTimeout: 60000
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    hotel-service:
      path: /hotel-management/**
      sensitiveHeaders: Cookie,Set-Cookie,Authorization
      serviceId: hotel-service
      stripPrefix: true

jwt:
  token:
    secret: jwtapp
    expired: 3600000

